version: '2'
services:
  registrator:
    image: gliderlabs/registrator
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-ip 127.0.0.1 zookeeper://127.0.0.1:2181/services"
